SPIKESDF_COLUMNS = (
    'Animal ID',
    'Sex',
    'Position',
    'Unit ID',
    'Unit Type',
    'Test',
    'Test Stimulus',
    'Test Frequency',
    'Minor Test Frequency',
    'Test Amplitude',
    'Test ID',
    'Repetition',
    'Trial ID',
    'Phase',
    'Epoch Stimulus',
    'Phase ID',
    'Epoch Number',
    'Epoch ID',
    'Epoch Frequency',
    'Epoch Amplitude',
    'Total Epochs',
    'Latency (ms)',
    'Size (μV)'
)
SPIKESDF_TYPES = {
    'Animal ID': 'string',
    'Position': 'uint64',
    'Unit ID': 'string',
    'Unit Type': 'string',
    'Test Frequency': 'float64',
    'Minor Test Frequency': 'float64',
    'Test Amplitude': 'float64',
    'Test ID': 'string',
    'Repetition': 'uint64',
    'Trial ID': 'string',
    'Phase ID': 'string',
    'Epoch Number': 'uint64',
    'Epoch ID': 'string',
    'Epoch Frequency': 'float64',
    'Epoch Amplitude': 'float64',
    'Total Epochs': 'uint64',
    'Latency (ms)': 'float64',
    'Size (μV)': 'float64'
}

FIG3_FITTEDDF_COLUMNS = (
    'animal_id',
    'unit_id',
    'test_id',
    'sex',
    'unit_type',
    'conduction_velocity',
    'a',
    'a_std',
    'k',
    'k_std',
    'c',
    'c_std',
    'rmse'
)
FIG3_FITTEDDF_TYPES = {
    'animal_id': 'string',
    'unit_id': 'string',
    'test_id': 'string',
    'unit_type': 'string',
    'conduction_velocity': 'float64',
    'a': 'float64',
    'a_std': 'float64',
    'k': 'float64',
    'k_std': 'float64',
    'c': 'float64',
    'c_std': 'float64',
    'rmse': 'float64'
}
FIG3_BINNEDDF_COLUMNS = (
    'animal_id',
    'unit_id',
    'test_id',
    'trial_id',
    'sex',
    'unit_type',
    'conduction_velocity',
    'time',
    'exp_time',
    'response_probability',
    'log_probability'
)
FIG3_BINNEDDF_TYPES = {
    'animal_id': 'string',
    'unit_id': 'string',
    'test_id': 'string',
    'trial_id': 'string',
    'unit_type': 'string',
    'conduction_velocity': 'float64',
    'time': 'float64',
    'exp_time': 'float64',
    'response_probability': 'float64',
    'log_probability': 'float64'
}

FIG4_OUTPUTDF_COLUMNS = (
    'animal_id',
    'unit_id',
    'test_id',
    'trial_id',
    'sex',
    'unit_type',
    'conduction_velocity',
    'absolute_charge',
    'response_probability_all',
    'response_probability_initial'
)
FIG4_OUTPUTDF_TYPES = {
    'animal_id': 'string',
    'unit_id': 'string',
    'test_id': 'string',
    'trial_id': 'string',
    'unit_type': 'string',
    'conduction_velocity': 'float64',
    'absolute_charge': 'float64',
    'response_probability_all': 'float64',
    'response_probability_initial': 'float64'
}
FIG4_OUTPUTDF_ALTERNATE_COLUMNS = (
    'animal_id',
    'unit_id',
    'test_id',
    'trial_id',
    'sex',
    'unit_type',
    'conduction_velocity',
    'absolute_charge',
    'response_probability_all',
    'response_probability_final'
)
FIG4_OUTPUTDF_ALTERNATE_TYPES = {
    'animal_id': 'string',
    'unit_id': 'string',
    'test_id': 'string',
    'trial_id': 'string',
    'unit_type': 'string',
    'conduction_velocity': 'float64',
    'absolute_charge': 'float64',
    'response_probability_all': 'float64',
    'response_probability_final': 'float64'
}

FIG5_OUTPUTDF_COLUMNS = (
    'animal_id',
    'unit_id',
    'test_id',
    'trial_id',
    'sex',
    'unit_type',
    'test',
    'stimulus',
    'conduction_velocity',
    'response_probability'
)
FIG5_OUTPUTDF_TYPES = {
    'animal_id': 'string',
    'unit_id': 'string',
    'test_id': 'string',
    'trial_id': 'string',
    'unit_type': 'string',
    'conduction_velocity': 'float64',
    'response_probability': 'float64'
}

FIG6_FITTEDDF_COLUMNS = (
    'animal_id',
    'unit_id',
    'test_id',
    'sex',
    'unit_type',
    'initial_conduction_velocity',
    'initial_amplitude',
    'initial_latency',
    'recording_distance',
    'test',
    'test_frequency',
    'test_amplitude',
    'latency_k',
    'latency_k_std',
    'latency_normal_a',
    'latency_normal_a_std',
    'latency_normal_rmse',
    'latency_normal_steady_cv',
    'latency_actual_a',
    'latency_actual_c',
    'latency_actual_rmse',
    'latency_actual_steady_cv',
    'amplitude_actual_slope',
    'amplitude_actual_slope_std',
    'amplitude_actual_intercept',
    'amplitude_actual_intercept_std',
    'amplitude_actual_mean',
    'amplitude_actual_rmse',
    'amplitude_actual_rsquared',
    'amplitude_normal_slope',
    'amplitude_normal_intercept',
    'amplitude_normal_mean',
    'amplitude_normal_rmse',
    'amplitude_normal_rsquared'
)

FIG6_FITTEDDF_TYPES = {
    'animal_id': 'string',
    'unit_id': 'string',
    'test_id': 'string',
    'unit_type': 'string',
    'initial_conduction_velocity': 'float64',
    'initial_amplitude': 'float64',
    'initial_latency': 'float64',
    'recording_distance': 'float64',
    'test_frequency': 'float64',
    'test_amplitude': 'float64',
    'latency_k': 'float64',
    'latency_k_std': 'float64',
    'latency_normal_a': 'float64',
    'latency_normal_a_std': 'float64',
    'latency_normal_rmse': 'float64',
    'latency_normal_steady_cv': 'float64',
    'latency_actual_a': 'float64',
    'latency_actual_c': 'float64',
    'latency_actual_rmse': 'float64',
    'latency_actual_steady_cv': 'float64',
    'amplitude_actual_slope': 'float64',
    'amplitude_actual_slope_std': 'float64',
    'amplitude_actual_intercept': 'float64',
    'amplitude_actual_intercept_std': 'float64',
    'amplitude_actual_mean': 'float64',
    'amplitude_actual_rmse': 'float64',
    'amplitude_actual_rsquared': 'float64',
    'amplitude_normal_slope': 'float64',
    'amplitude_normal_intercept': 'float64',
    'amplitude_normal_mean': 'float64',
    'amplitude_normal_rmse': 'float64',
    'amplitude_normal_rsquared': 'float64'
}
FIG6_SWEEPSDF_COLUMNS = (
    'animal_id',
    'unit_id',
    'test_id',
    'trial_id',
    'sex',
    'unit_type',
    'initial_conduction_velocity',
    'initial_amplitude',
    'initial_latency',
    'recording_distance',
    'test',
    'test_frequency',
    'test_amplitude',
    'absolute_charge',
    'latency_actual_mean',
    'latency_normal_mean',
    'cv_actual_mean',
    'cv_normal_mean',
    'amplitude_actual_mean',
    'amplitude_normal_mean'
)
FIG6_SWEEPSDF_TYPES = {
    'animal_id': 'string',
    'unit_id': 'string',
    'test_id': 'string',
    'trial_id': 'string',
    'unit_type': 'string',
    'initial_conduction_velocity': 'float64',
    'initial_amplitude': 'float64',
    'initial_latency': 'float64',
    'recording_distance': 'float64',
    'test_frequency': 'float64',
    'test_amplitude': 'float64',
    'absolute_charge': 'float64',
    'latency_actual_mean': 'float64',
    'latency_normal_mean': 'float64',
    'cv_actual_mean': 'float64',
    'cv_normal_mean': 'float64',
    'amplitude_actual_mean': 'float64',
    'amplitude_normal_mean': 'float64'
}
